### PR TITLE
CI: set -Wno-error=maybe-uninitialized

### LINKED ISSUE #214: build failure after update to msys2-w32api
After msys2-w32api was updated to 11.0.1.r750.g05598db99-1 I am seeing a build failure in msys2-runtime:
```
  /C/_/msys2-runtime/src/msys2-runtime/winsup/cygwin/exceptions.cc: In member function 'int _cygtls::call_signal_handler()':
  /C/_/msys2-runtime/src/msys2-runtime/winsup/cygwin/exceptions.cc:1736:33: error: '<anonymous>' may be used uninitialized [-Werror=maybe-uninitialized]
   1736 |               RtlCaptureContext ((PCONTEXT) &context.uc_mcontext);
        |               ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by lazka**
After the update of msys2-w32api from v11.0.1 to current master (and soon to be v12) we get: winsup/cygwin/exceptions.cc:1736:33: error: '<anonymous>' may be used uninitialized [-Werror=maybe-uninitialized]

Ignore it like the rest.

Fixes #214

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I am curious why this is still a draft/not merged?

**Comment by lazka** [comment]
I pinged martin back then to see if this might be a mingw-w64 issue or something, but he didn't respond, so let's just merge it.
